runtime: nodejs18
entrypoint: node index.js

env_variables:
  DATABASE_URL: 'mysql://61o240iuj1ycuaad48y7:pscale_pw_3AclEcceHg4DmAB5uvi7CVVETPcVphuBrM9PPBlzAxq@aws.connect.psdb.cloud/deploy-test?sslaccept=strict'
  AUTH0_AUDIENCE: 'https://api.moviereview'
  AUTH0_ISSUER: 'https://dev-jll33zjd0dtbxwjj.us.auth0.com'
  PORT: '8080'
